### ISSUE TITLE
README needed

### ISSUE THREAD

**Issue by CWWhitney** [AditiBista/masterthesis#3]
@AditiBista 
Make a README file and add the conceptual model there

**Comment by AditiBista** [comment]
Readme content will be added soon

**Comment by CWWhitney** [comment]
![Screenshot 2023-11-28 at 1 00 10 PM](https://github.com/AditiBista/masterthesis/assets/19190662/716a6545-c7c0-4a2e-924b-3dbcc31f123c)
Add the conceptual model to the readme too :)
